### ISSUE TITLE
asdasd

### ISSUE THREAD

**Issue by calmh** [calmh/sandbox#1]
asdasd

**Comment by calmh** [comment]
foo

**Comment by calmh** [comment]
@st-review: do this thing

**Comment by calmh** [comment]
jnkjn

**Comment by calmh** [comment]
@st-review: foo bar

**Comment by calmh** [comment]
@st-review: merge this

**Comment by calmh** [comment]
@st-review: merge this

**Comment by calmh** [comment]
@st-review add author foo

**Comment by st-review** [comment]
Syntax:

```
st-review: add author

author-nick

Author Name
author.email@example.com
```

**Comment by calmh** [comment]
@st-review add author

calmh

**Comment by st-review** [comment]
Syntax:

```
st-review: add author

author-nick

Author Name
author.email@example.com
```

**Comment by calmh** [comment]
@st-review add author

calmh
test

**Comment by st-review** [comment]
Syntax:

```
st-review: add author

author-nick

Author Name
author.email@example.com
```

**Comment by calmh** [comment]
@st-review add author

calmh
foo
bar

**Comment by calmh** [comment]
@st-review add author

calmh
foo
bar

**Comment by st-review** [comment]
Syntax:

```
@st-review: add author

author-nick
Author Name
author.email@example.com
```

**Comment by calmh** [comment]
@st-review add author

calmh
foo baz
bar

**Comment by st-review** [comment]
Syntax:

```
@st-review: add author

author-nick
Author Name
author.email@example.com
```

**Comment by calmh** [comment]
@st-review add author

calmh
foo
bar@example.com

**Comment by st-review** [comment]
Syntax:

```
@st-review: add author

author-nick
Author Name
author.email@example.com
```

**Comment by calmh** [comment]
@st-review add author

calmh
foo bar
bar@example.com

**Comment by calmh** [comment]
@st-review add author

calmh
foo bar
bar@example.com

**Comment by calmh** [comment]
@st-review add author

calmh
foo bar
bar@example.com

**Comment by calmh** [comment]
@st-review add author

calmh
foo bar
bar@example.com

**Comment by calmh** [comment]
@st-review add author

calmh
foo bar
bar@example.com

**Comment by calmh** [comment]
@st-review äpple päron banan!

**Comment by st-review** [comment]
I'm sorry, @calmh. I'm afraid I don't know what you mean. I know how to `merge` things!

**Comment by calmh-sandbox** [comment]
@st-review merge this!

**Comment by st-review** [comment]
I'm sorry, @calmh-sandbox. I'm afraid I can't do that.

**Comment by calmh** [comment]
test

**Comment by calmh** [comment]
@st-review test

**Comment by st-review** [comment]
I'm sorry, @calmh. I'm afraid I don't know what you mean. I know how to `merge` things!

**Comment by calmh** [comment]
@st-review test

**Comment by st-review** [comment]
I'm sorry, @calmh. I'm afraid I don't know what you mean. I know how to `merge`, `squash`.

**Comment by calmh** [comment]
@st-review merge this

**Comment by calmh** [comment]
@st-review merge this

**Comment by st-review** [comment]
Merge failed:

```
Nothing to merge, as far as I can tell.
```
